export enum ErrorCode {
  DISCORD_USER_NOT_FOUND = 'DISCORD_USER_NOT_FOUND',
  DISCORD_USER_EXISTS = 'DISCORD_USER_EXISTS',
  DISCORD_SETTING_NOT_FOUND = 'DISCORD_SETTING_NOT_FOUND',
  DISCORD_SETTING_EXISTS = 'DISCORD_SETTING_EXISTS',
}
