export enum ErrorCode {
  DISCORD_USER_NOT_FOUND = 'DISCORD_USER_NOT_FOUND',
  DISCORD_USER_EXISTS = 'DISCORD_USER_EXISTS',
  DISCORD_SETTING_NOT_FOUND = 'DISCORD_SETTING_NOT_FOUND',
  DISCORD_SETTING_EXISTS = 'DISCORD_SETTING_EXISTS',
  DISCORD_CHATGPT_TRANSACTION_NOT_FOUND = 'DISCORD_CHATGPT_TRANSACTION_NOT_FOUND',
  DISCORD_CHATGPT_TRANSACTION_EXISTS = 'DISCORD_CHATGPT_TRANSACTION_EXISTS',
  DISCORD_CHATGPT_TRANSACTION_SUMMARY_NOT_FOUND = 'DISCORD_CHATGPT_TRANSACTION_SUMMARY_NOT_FOUND',
  DISCORD_CHATGPT_TRANSACTION_SUMMARY_EXISTS = 'DISCORD_CHATGPT_TRANSACTION_SUMMARY_EXISTS',
  DISCORD_CHANNEL_NOT_FOUND = 'DISCORD_CHANNEL_NOT_FOUND',
}
