import { MovieStatusType } from '@Enums/radarr/movie';
import { AddMovieOptions } from './add-movie-options.type';
import { AlternateTitle } from './alternate-title.type';
import { Language } from './language.type';
import { MediaCover } from './media-cover.type';
import { MovieCollection } from './movie-collection.type';
import { MovieFile } from './movie-file.type';
import { MovieStatistics } from './movie-statistics.type';
import { Ratings } from './ratings.type';

export type Movie = {
  id: number;
  title: string | null;
  originalTitle: string | null;
  originalLanguage: Language;
  alternateTitles: AlternateTitle[];
  secondaryYear: number | null;
  secondaryYearSourceId: number;
  sortTitle: string | null;
  sizeOnDisk: number | null;
  status: MovieStatusType;
  overview: string | null;
  inCinemas: string | null;
  physicalRelease: string | null;
  digitalRelease: string | null;
  releaseDate: string | null;
  physicalReleaseNote: string | null;
  images: MediaCover[] | null;
  website: string | null;
  remotePoster: string | null;
  year: number;
  youTubeTrailerId: string | null;
  studio: string | null;
  path: string | null;
  qualityProfileId: number;
  hasFile: boolean | null;
  movieFileId: number;
  monitored: boolean;
  minimumAvailability: MovieStatusType;
  isAvailable: boolean;
  folderName: string | null;
  runtime: number;
  cleanTitle: string | null;
  imdbId: string | null;
  tmdbId: number;
  titleSlug: string | null;
  rootFolderPath: string | null;
  folder: string | null;
  certification: string | null;
  genres: string[] | null;
  keywords: string[] | null;
  tags: number[] | null;
  added: string;
  addOptions: AddMovieOptions;
  ratings: Ratings;
  movieFile: MovieFile;
  collection: MovieCollection;
  popularity: number;
  lastSearchTime: string | null;
  statistics: MovieStatistics;
};
